[package]
name = "brainative"
version = "0.1.0"
authors = ["Sam Rankin <sam.rankin@me.com>"]

[dependencies]
# forkengine = { path = "../forkengine" }
forkengine = { git = "https://github.com/samrankin1/forkengine.git" }
